
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const KEY='sst4_state';
const seed=[{id:'b1',title:'Проект Рози',author:'Грэм Симсион',pages:320,read:210,status:'reading',cover:'',year:2013},{id:'b2',title:'Атомные привычки',author:'Джеймс Клир',pages:320,read:320,status:'finished',cover:'',year:2018},{id:'b3',title:'Марсианин',author:'Энди Вейер',pages:384,read:0,status:'planned',cover:'',year:2011},{id:'b4',title:'1984',author:'Джордж Оруэлл',pages:328,read:328,status:'finished',cover:'',year:1949}];
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{books:seed,notes:[],goalBooks:30,goalPages:20,sessions:{},seconds:0,history:[],collections:[],series:[],profile:{name:'Читатель',avatar:''},reviews:{},theme:'light'};
let cloud=null,user=null,syncTimer=null,timerId=null,timerStart=0,timerElapsed=0,activeBook=null,month=new Date(),libraryFilter='all',noteFilter='all';
function saveLocal(){localStorage.setItem(KEY,JSON.stringify(state)); if(user&&cloud){clearTimeout(syncTimer);syncTimer=setTimeout(syncCloud,500)}}
function save(){saveLocal(); renderCurrent()}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function pct(b){return b.pages?Math.min(100,Math.round(b.read/b.pages*100)):0}
function cover(b,size='L'){return b.cover||''}
function coverHtml(b,small=false){return b.cover?`<img src="${esc(b.cover)}" alt="">`:`<div class="cover-title">${esc(b.title)}</div>`}
function fmtTime(sec){sec=Math.round(sec);if(sec<60)return sec+' сек';if(sec<3600)return Math.floor(sec/60)+' мин';return Math.floor(sec/3600)+' ч '+Math.floor(sec%3600/60)+' мин'}
function dateKey(d=new Date()){return d.toISOString().slice(0,10)}
function toast(msg){let el=document.createElement('div');el.className='toast';el.textContent=msg;$('#toastRoot').append(el);setTimeout(()=>el.remove(),2400)}
function completedBooks(){return state.books.filter(b=>b.status==='finished'||b.read>=b.pages).length}
function totalPages(){return state.books.reduce((n,b)=>n+Math.min(b.read,b.pages),0)}
function streak(){let days=Object.keys(state.sessions).filter(k=>(state.sessions[k]?.pages||0)>0).sort();if(!days.length)return 0;let set=new Set(days),d=new Date(days.at(-1));let n=0;while(set.has(dateKey(d))){n++;d.setDate(d.getDate()-1)}return n}
function stats(){let today=state.sessions[dateKey()]||{};let year=new Date().getFullYear();let ybooks=state.books.filter(b=>b.status==='finished'&&b.finishedAt&&new Date(b.finishedAt).getFullYear()===year).length;let sec=state.seconds;let pages=totalPages();return {todayPages:today.pages||0,ybooks,ypages:Object.entries(state.sessions).filter(([k])=>k.startsWith(year+'-')).reduce((n,[,v])=>n+(v.pages||0),0),books:completedBooks(),pages,time:sec,speed:sec?Math.round(pages/(sec/3600)):0,streak:streak()}}
async function initCloud(){try{if(!window.supabase||!window.SUPABASE_URL){setSync('Локально');return}cloud=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);let s=await cloud.auth.getSession();user=s.data.session?.user||null;if(user)await loadCloud();setSync(user?'Синхронизировано':'Локально');cloud.auth.onAuthStateChange(async(_e,session)=>{user=session?.user||null;if(user)await loadCloud();setSync(user?'Синхронизировано':'Локально');renderCurrent()})}catch(e){console.error(e);setSync('Локально')}}
function setSync(t){let e=$('#syncBadge');if(e)e.textContent='● '+t;let a=$('#authOpen');if(a)a.textContent=user?'Профиль':'Войти'}
async function loadCloud(){if(!cloud||!user)return;let {data,error}=await cloud.from('user_data').select('data').eq('user_id',user.id).maybeSingle();if(error)return;if(data?.data&&Object.keys(data.data).length){state={...state,...data.data};saveLocal()}let p=await cloud.from('profiles').select('*').eq('id',user.id).maybeSingle();if(p.data){state.profile={...state.profile,name:p.data.display_name||state.profile.name,avatar:p.data.avatar||state.profile.avatar};saveLocal()}}
async function syncCloud(){if(!cloud||!user)return;await cloud.from('user_data').upsert({user_id:user.id,data:state,updated_at:new Date().toISOString()},{onConflict:'user_id'});await cloud.from('profiles').upsert({id:user.id,display_name:state.profile.name||'Читатель',avatar:state.profile.avatar||null,updated_at:new Date().toISOString()},{onConflict:'id'});setSync('Синхронизировано')}
function modal(html){let wrap=document.createElement('dialog');wrap.className='modal';wrap.innerHTML=html;document.body.append(wrap);wrap.addEventListener('click',e=>{if(e.target===wrap)wrap.close()});wrap.showModal();return wrap}
function bookCard(b){return `<article class="book"><div class="cover">${coverHtml(b)}</div><div class="book-body"><h3>${esc(b.title)}</h3><p>${esc(b.author)}</p><div class="progress"><i style="width:${pct(b)}%"></i></div><div class="book-meta"><span>${b.status==='finished'?'Прочитано':b.status==='reading'?`${b.read} / ${b.pages} стр.`:'В планах'}</span><b>${pct(b)}%</b></div><div class="book-actions"><button class="icon-btn" data-edit="${b.id}">Редактировать</button><button class="icon-btn" data-detail="${b.id}">Открыть</button></div></div></article>`}
function renderHome(){
  let s=stats();
  let reading=state.books.slice(0,8);
  $('#homeBookCount').textContent=state.books.length+' '+(state.books.length===1?'книга':state.books.length<5?'книги':'книг');
  $('#homeBooks').innerHTML=reading.length?reading.map(bookCard).join(''):'<div class="empty">Сейчас ничего не читаешь. Выбери книгу из библиотеки.</div>';
  $('#homeProfile').innerHTML=`<div class="profile-head"><div><span class="kicker">МОЙ ПРОФИЛЬ</span><h3>${esc(state.profile.name||'Читатель')}</h3><small>${user?.email||'Личный профиль'}</small></div><a href="profile.html" class="profile-gear">⚙</a></div><div class="home-profile-main"><img src="${esc(state.profile.avatar||'hero-library.png')}" alt="" class="home-profile-photo"><div><b>${s.books}</b><span>Прочитано книг</span></div><div><b>${s.pages.toLocaleString('ru-RU')}</b><span>Страниц</span></div><div><b>${fmtTime(s.time)}</b><span>Время чтения</span></div></div><div class="profile-quote">«Хорошие книги делают жизнь лучше» <span>♥</span></div><div class="profile-section-title">Мои достижения <a href="profile.html">Смотреть все</a></div><div class="mini-achievements">${achievements().slice(0,5).map(a=>`<div class="mini-achievement ${a[2]?'':'locked'}"><div>${a[0]}</div><small>${esc(a[1])}</small></div>`).join('')}</div>`;
  $('#homeSessionPanel').innerHTML=`<div class="cozy-session-bg"><span class="kicker">СЕССИЯ ЧТЕНИЯ</span><h3>${reading[0]?esc(reading[0].title):'Начни новую сессию'}</h3><p>${reading[0]?esc(reading[0].author):'Выбери книгу из библиотеки'}</p><div class="timer-preview">${fmtClock(timerElapsed)}</div><div class="session-quote">«Маленькие шаги каждый день<br>приводят к большим результатам»</div><div class="session-controls"><a class="round-control" href="session.html">▶</a><a class="session-primary" href="session.html">${activeBook?'Продолжить':'Начать сессию'}</a></div></div>`;
  $('#homeStatsPanel').innerHTML=`<div class="panel-head"><div><span class="kicker">СТАТИСТИКА</span><h3>Твой ритм</h3></div><a href="stats.html">Подробнее →</a></div><div class="home-stat-cards"><div><b>${s.books}</b><span>Книги</span></div><div><b>${s.pages.toLocaleString('ru-RU')}</b><span>Страницы</span></div><div><b>${fmtTime(s.time)}</b><span>Время чтения</span></div><div><b>${s.speed||'—'}</b><span>Стр/ч</span></div></div>`;
  let now=new Date(), days=['Пн','Вт','Ср','Чт','Пт','Сб','Вс']; let week=''; for(let i=0;i<7;i++){let d=new Date(now);d.setDate(now.getDate()-((now.getDay()+6)%7)+i);let k=dateKey(d),p=state.sessions[k]?.pages||0;week+=`<div class="week-cell ${p?'has-read':''}"><b>${days[i]}</b><span>${d.getDate()}</span><small>${p||''}</small></div>`;}
  $('#homeCalendarPanel').innerHTML=`<div class="panel-head"><div><span class="kicker">КАЛЕНДАРЬ ЧТЕНИЯ</span><h3>${new Intl.DateTimeFormat('ru-RU',{month:'long'}).format(now)}</h3></div><a href="calendar.html">→</a></div><div class="week-strip">${week}</div><div class="streak-callout"><span>🔥</span><div><b>Текущая серия</b><strong>${s.streak} ${s.streak===1?'день':'дней'}</strong></div></div>`;
  $('#homeSessions').innerHTML=`<div class="panel-head"><div><span class="kicker">ИСТОРИЯ</span><h3>Последние сессии</h3></div><a href="stats.html">Все сессии →</a></div>${historyHtml()}`;
  $('#homeSearch').oninput=()=>{let q=$('#homeSearch').value.toLowerCase();let arr=state.books.filter(b=>(b.title+' '+b.author).toLowerCase().includes(q));$('#homeBooks').innerHTML=arr.slice(0,8).map(bookCard).join('')||'<div class="empty">Ничего не найдено.</div>';};
  $$('[data-edit]').forEach(b=>b.onclick=()=>openBookForm(state.books.find(x=>String(x.id)===String(b.dataset.edit))));
  $$('[data-detail]').forEach(b=>b.onclick=()=>openBookDetail(state.books.find(x=>String(x.id)===String(b.dataset.detail))));
}
function renderLibrary(){let q=($('#librarySearch')?.value||'').toLowerCase();let arr=state.books.filter(b=>(libraryFilter==='all'||b.status===libraryFilter)&&(b.title+' '+b.author+' '+(b.isbn||'')).toLowerCase().includes(q));$('#libraryBooks').innerHTML=arr.length?arr.map(bookCard).join(''):'<div class="empty">Книг не найдено.</div>';$$('[data-filter]').forEach(x=>x.onclick=()=>{libraryFilter=x.dataset.filter;$$('[data-filter]').forEach(y=>y.classList.remove('active'));x.classList.add('active');renderLibrary()});$('#librarySearch').oninput=renderLibrary;$$('[data-edit]').forEach(b=>b.onclick=()=>openBookForm(state.books.find(x=>String(x.id)===String(b.dataset.edit))));$$('[data-detail]').forEach(b=>b.onclick=()=>openBookDetail(state.books.find(x=>String(x.id)===String(b.dataset.detail))))}
function openBookForm(book=null){let edit=!!book;let d=modal(`<div class="modal-head"><div><span class="kicker">${edit?'РЕДАКТИРОВАНИЕ':'НОВАЯ КНИГА'}</span><h3>${edit?'Редактировать книгу':'Добавить книгу'}</h3></div><button class="close">×</button></div><div class="modal-body"><form id="bookForm"><div class="form-grid"><div class="field"><label>Название</label><input id="bfTitle" required value="${esc(book?.title||'')}"></div><div class="field"><label>Автор</label><input id="bfAuthor" value="${esc(book?.author||'')}"></div><div class="field"><label>Страниц</label><input id="bfPages" type="number" min="1" value="${book?.pages||300}"></div><div class="field"><label>Прочитано</label><input id="bfRead" type="number" min="0" value="${book?.read||0}"></div><div class="field"><label>Статус</label><select id="bfStatus"><option value="planned">В планах</option><option value="reading">Читаю</option><option value="finished">Прочитано</option><option value="abandoned">Брошено</option></select></div><div class="field"><label>Жанр</label><input id="bfGenre" value="${esc(book?.genre||'')}"></div></div><div class="cover-upload" style="margin-top:14px"><div class="cover-preview" id="coverPreview">${book?.cover?`<img src="${esc(book.cover)}">`:`<div class="cover-title">Обложка</div>`}</div><p>Можно загрузить собственную обложку.</p><input id="bfCover" type="file" accept="image/*"></div><div class="actions" style="margin-top:16px"><button class="btn">${edit?'Сохранить':'Добавить'}</button>${edit?'<button type="button" class="secondary danger" id="deleteBook">Удалить книгу</button>':''}</div></form></div>`);let currentCover=book?.cover||'';$('#bfStatus',d).value=book?.status||'planned';$('#bfCover',d).onchange=async e=>{let f=e.target.files[0];if(f){currentCover=await resizeImage(f);$('#coverPreview',d).innerHTML=`<img src="${currentCover}">`}};$('.close',d).onclick=()=>d.close();$('#bookForm',d).onsubmit=e=>{e.preventDefault();let pages=Math.max(1,+$('#bfPages',d).value||300),read=Math.min(pages,Math.max(0,+$('#bfRead',d).value||0)),status=$('#bfStatus',d).value;let obj={title:$('#bfTitle',d).value.trim(),author:$('#bfAuthor',d).value.trim()||'Неизвестный автор',pages,read,status,genre:$('#bfGenre',d).value.trim(),cover:currentCover};if(read>=pages){obj.status='finished';obj.finishedAt=book?.finishedAt||new Date().toISOString()}if(edit)Object.assign(book,obj);else state.books.unshift({id:'b'+Date.now(),...obj});save();d.close();toast(edit?'Книга обновлена':'Книга добавлена')};if(edit)$('#deleteBook',d).onclick=()=>{if(confirm('Удалить книгу?')){state.books=state.books.filter(x=>x.id!==book.id);state.history=state.history.filter(x=>x.bookId!==book.id);save();d.close();toast('Книга удалена')}}}
async function resizeImage(file){return new Promise(res=>{let r=new FileReader();r.onload=()=>{let img=new Image();img.onload=()=>{let c=document.createElement('canvas'),max=600,s=Math.min(1,max/Math.max(img.width,img.height));c.width=Math.round(img.width*s);c.height=Math.round(img.height*s);c.getContext('2d').drawImage(img,0,0,c.width,c.height);res(c.toDataURL('image/jpeg',.78))};img.src=r.result};r.readAsDataURL(file)})}
function openBookDetail(b){let rev=state.reviews[b.id]||{};let s=state.history.filter(x=>x.bookId===b.id);let time=s.reduce((n,x)=>n+x.duration,0),pages=s.reduce((n,x)=>n+(x.pages||0),0);let d=modal(`<div class="modal-head"><div><span class="kicker">КНИГА</span><h3>${esc(b.title)}</h3></div><button class="close">×</button></div><div class="modal-body"><div class="session-picker"><div class="cover">${coverHtml(b)}</div><div><h3>${esc(b.author)}</h3><p>${b.pages} страниц · ${pct(b)}% прочитано</p><div class="progress"><i style="width:${pct(b)}%"></i></div><p>${s.length} сессий · ${fmtTime(time)} · ${pages} стр. по сессиям</p></div></div><div class="stat-grid" style="margin-top:15px"><div class="stat-card"><span>Сессии</span><strong>${s.length}</strong></div><div class="stat-card"><span>Время</span><strong>${fmtTime(time)}</strong></div><div class="stat-card"><span>Оценка</span><strong>${rev.rating||'—'}</strong></div><div class="stat-card"><span>Жанр</span><strong>${esc(b.genre||'—')}</strong></div></div><div class="actions" style="margin-top:16px"><button class="btn" id="editInside">Редактировать</button><button class="secondary" id="reviewInside">Добавить отзыв</button></div></div>`);$('.close',d).onclick=()=>d.close();$('#editInside',d).onclick=()=>{d.close();openBookForm(b)};$('#reviewInside',d).onclick=()=>{d.close();openReview(b)}}
function openReview(b){let old=state.reviews[b.id]||{};let d=modal(`<div class="modal-head"><div><span class="kicker">ЛИЧНАЯ ОЦЕНКА</span><h3>${esc(b.title)}</h3></div><button class="close">×</button></div><div class="modal-body"><form id="reviewForm"><div class="field"><label>Оценка 1–5</label><select id="rating"><option>5</option><option>4</option><option>3</option><option>2</option><option>1</option></select></div><div class="field" style="margin-top:12px"><label>Отзыв</label><textarea id="reviewText">${esc(old.text||'')}</textarea></div><button class="btn" style="margin-top:14px">Сохранить отзыв</button></form></div>`);$('#rating',d).value=old.rating||5;$('.close',d).onclick=()=>d.close();$('#reviewForm',d).onsubmit=e=>{e.preventDefault();state.reviews[b.id]={rating:+$('#rating',d).value,text:$('#reviewText',d).value};state.notes.unshift({id:'n'+Date.now(),bookId:b.id,book:b.title,type:'review',text:$('#reviewText',d).value,date:new Date().toISOString()});save();d.close();toast('Отзыв сохранён')}}
function renderDiscover(){let search=async q=>{if(!q)return;$('#searchResults').innerHTML='<div class="empty">Ищу книги…</div>';try{let isbn=/^(97[89])?[\dXx -]{9,}$/.test(q);let u='https://openlibrary.org/search.json?'+(isbn?'isbn=':'q=')+encodeURIComponent(q)+'&limit=12&fields=key,title,author_name,first_publish_year,cover_i,isbn,number_of_pages_median,publisher';let data=await (await fetch(u)).json();window.results=data.docs||[];$('#searchResults').innerHTML=window.results.length?window.results.map((d,i)=>{let is=(d.isbn||[]).find(x=>String(x).length===13)||'';let cv=d.cover_i?`https://covers.openlibrary.org/b/id/${d.cover_i}-M.jpg`:'';return `<div class="row-card"><div class="thumb">${cv?`<img class="thumb" src="${cv}">`:''}</div><div><h3>${esc(d.title||'Без названия')}</h3><p>${esc((d.author_name||['Неизвестный автор'])[0])} ${d.first_publish_year?'· '+d.first_publish_year:''}</p></div><button class="btn" data-add-result="${i}">＋ Добавить</button></div>`}).join(''):'<div class="empty">Ничего не найдено.</div>';$$('[data-add-result]').forEach(x=>x.onclick=()=>addApiBook(window.results[+x.dataset.addResult]))}catch(e){$('#searchResults').innerHTML='<div class="empty">Не удалось получить данные. Проверь интернет.</div>'}};$('#findBtn').onclick=()=>search($('#bookSearch').value.trim());$('#bookSearch').onkeydown=e=>{if(e.key==='Enter')search(e.target.value.trim())};$('#scanBtn').onclick=()=>scanISBN()}
function addApiBook(d){let isbn=(d.isbn||[]).find(x=>String(x).length===13)||'';if(state.books.some(b=>isbn&&b.isbn===isbn)){toast('Книга уже в библиотеке');return}state.books.unshift({id:'b'+Date.now(),title:d.title||'Без названия',author:(d.author_name||['Неизвестный автор'])[0],pages:d.number_of_pages_median||300,read:0,status:'planned',cover:d.cover_i?`https://covers.openlibrary.org/b/id/${d.cover_i}-L.jpg`:'',isbn,year:d.first_publish_year||'',publisher:(d.publisher||[])[0]||''});save();toast('Книга добавлена в библиотеку')}
async function scanISBN(){let d=modal(`<div class="modal-head"><h3>Сканирование ISBN</h3><button class="close">×</button></div><div class="modal-body"><video id="scanVideo" style="width:100%;border-radius:14px;background:#111" playsinline></video><p id="scanText">Запрашиваем камеру…</p><input class="search" id="manualIsbn" placeholder="Или введи ISBN вручную"><button class="btn" id="manualIsbnBtn" style="margin-top:10px">Найти ISBN</button></div>`);$('.close',d).onclick=()=>{stopScan();d.close()};$('#manualIsbnBtn',d).onclick=()=>{$('#bookSearch').value=$('#manualIsbn',d).value;d.close();stopScan();$('#findBtn').click()};if(!('BarcodeDetector'in window)){ $('#scanText',d).textContent='Браузер не поддерживает сканирование. Используй ручной ISBN.';return}try{let formats=await BarcodeDetector.getSupportedFormats();let det=new BarcodeDetector({formats:formats.filter(x=>x==='ean_13'||x==='ean_8')});let stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});let v=$('#scanVideo',d);v.srcObject=stream;await v.play();async function loop(){if(!d.open)return;try{let c=await det.detect(v);if(c[0]){$('#bookSearch').value=c[0].rawValue;stop();d.close();$('#findBtn').click();return}}catch{}requestAnimationFrame(loop)}function stop(){stream.getTracks().forEach(t=>t.stop());v.srcObject=null}loop()}catch{$('#scanText',d).textContent='Камера недоступна. Можно ввести ISBN вручную.'}}
function stopScan(){$$('video').forEach(v=>{if(v.srcObject)v.srcObject.getTracks().forEach(t=>t.stop())})}
function startSession(){let opts=state.books.filter(b=>b.status!=='finished');let d=modal(`<div class="modal-head"><div><span class="kicker">СЕССИЯ</span><h3>Что читаем?</h3></div><button class="close">×</button></div><div class="modal-body"><div class="field"><label>Книга</label><select id="pickBook">${opts.length?opts.map(b=>`<option value="${b.id}">${esc(b.title)} — ${esc(b.author)}</option>`).join(''):'<option value="">Нет книг для чтения</option>'}</select></div><div id="pickPreview" style="margin-top:15px"></div><button class="btn" id="goSession" style="margin-top:15px" ${opts.length?'':'disabled'}>Начать таймер</button></div>`);$('.close',d).onclick=()=>d.close();let preview=()=>{let b=state.books.find(x=>String(x.id)===$('#pickBook',d).value);$('#pickPreview',d).innerHTML=b?`<div class="row-card"><img class="thumb" src="${b.cover||'hero-library.png'}"><div><h3>${esc(b.title)}</h3><p>${b.read} / ${b.pages} стр.</p></div></div>`:''};$('#pickBook',d).onchange=preview;preview();$('#goSession',d).onclick=()=>{activeBook=state.books.find(x=>String(x.id)===$('#pickBook',d).value);d.close();timerStart=Date.now();timerElapsed=0;timerId=setInterval(updateTimer,1000);$('#sessionStart').hidden=true;$('#sessionStop').hidden=false;$('#sessionStatus').textContent='Читаем: '+activeBook.title;renderSessionPicker()}}
function updateTimer(){timerElapsed=Math.floor((Date.now()-timerStart)/1000);let e=$('#timer');if(e)e.textContent=fmtClock(timerElapsed)}function fmtClock(s){return [Math.floor(s/3600),Math.floor(s/60)%60,s%60].map(x=>String(x).padStart(2,'0')).join(':')}
function stopSession(){clearInterval(timerId);let d=modal(`<div class="modal-head"><div><span class="kicker">СЕССИЯ ЗАВЕРШЕНА</span><h3>Сохраним результат?</h3></div></div><div class="modal-body"><p>Время: <b>${fmtClock(timerElapsed)}</b></p><div class="form-grid"><div class="field"><label>Прочитано страниц</label><input id="sessPages" type="number" min="0" value="0"></div><div class="field"><label>Тип записи</label><select id="sessType"><option value="thought">Мысль</option><option value="quote">Цитата</option><option value="none">Без заметки</option></select></div></div><div class="field" style="margin-top:12px"><label>Заметка</label><textarea id="sessNote" placeholder="Что запомнилось?"></textarea></div><div class="actions" style="margin-top:14px"><button class="btn" id="saveSession">Сохранить</button><button class="secondary" id="discardSession">Отменить</button></div></div>`);$('#saveSession',d).onclick=()=>{let pages=Math.max(0,+$('#sessPages',d).value||0),b=activeBook;b.read=Math.min(b.pages,b.read+pages);if(b.read>=b.pages){b.status='finished';b.finishedAt=new Date().toISOString()}let k=dateKey();state.sessions[k]=state.sessions[k]||{pages:0,seconds:0};state.sessions[k].pages+=pages;state.sessions[k].seconds+=timerElapsed;state.seconds+=timerElapsed;let note=$('#sessNote',d).value.trim();state.history.unshift({id:'s'+Date.now(),bookId:b.id,book:b.title,duration:timerElapsed,pages,note,date:new Date().toISOString()});if(note&&$('#sessType',d).value!=='none')state.notes.unshift({id:'n'+Date.now(),bookId:b.id,book:b.title,type:$('#sessType',d).value,text:note,date:new Date().toISOString()});state.history=state.history.slice(0,100);timerElapsed=0;activeBook=null;$('#sessionStart').hidden=false;$('#sessionStop').hidden=true;save();d.close();toast('Сессия сохранена')};$('#discardSession',d).onclick=()=>{timerElapsed=0;activeBook=null;$('#sessionStart').hidden=false;$('#sessionStop').hidden=true;d.close()}}
function fmtDate(d){return new Date(d).toLocaleDateString('ru-RU',{day:'2-digit',month:'short'})}function historyHtml(){return state.history.slice(0,6).map(s=>`<div class="row-card"><div class="thumb">${esc(s.book[0]||'К')}</div><div><h3>${esc(s.book)}</h3><p>${fmtDate(s.date)} · ${fmtTime(s.duration)} · +${s.pages||0} стр.</p></div><span>${s.note?'✦':''}</span></div>`).join('')||'<div class="empty">Сессий пока нет.</div>'}
function renderSessionPicker(){let b=activeBook;$('#sessionPanel').innerHTML=`<div class="session-picker"><div class="cover">${b?coverHtml(b):''}</div><div><h3>${b?esc(b.title):'Сессия чтения'}</h3><p>${b?esc(b.author):'Выбери книгу перед стартом.'}</p></div></div><div class="timer-big" id="timer">${fmtClock(timerElapsed)}</div><div style="display:flex;justify-content:center;gap:10px"><button class="btn" id="sessionStart" ${b?'hidden':''}>Выбрать книгу и начать</button><button class="secondary" id="sessionStop" ${b?'':'hidden'}>Завершить</button></div><p id="sessionStatus" style="text-align:center;color:var(--muted)">${b?'Читаем прямо сейчас.':'Каждая сессия сохраняет время, страницы и заметку.'}</p>`;$('#sessionStart').onclick=startSession;$('#sessionStop').onclick=stopSession}
function renderSession(){renderSessionPicker();$('#recentSessions').innerHTML=historyHtml()}
function renderCalendar(){let y=month.getFullYear(),m=month.getMonth();$('#monthName').textContent=new Intl.DateTimeFormat('ru-RU',{month:'long',year:'numeric'}).format(month);let first=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate(),html='';for(let i=0;i<first;i++)html+='<div></div>';for(let d=1;d<=days;d++){let k=dateKey(new Date(y,m,d)),p=state.sessions[k]?.pages||0,cl=p>=20?'read3':p>=10?'read2':p?'read1':'';let t=new Date();let today=y===t.getFullYear()&&m===t.getMonth()&&d===t.getDate();html+=`<div class="day ${cl} ${today?'today':''}"><b>${d}</b>${p?`<small>${p} стр.</small>`:''}</div>`}$('#calendarGrid').innerHTML=html}
function renderStats(){let s=stats();$('#statCards').innerHTML=[['Книг прочитано',s.books,'завершённых'],['Страниц',s.pages,'в библиотеке'],['Время чтения',fmtTime(s.time),'по сессиям'],['Средняя скорость',s.speed?s.speed+' стр/ч':'—','по таймеру']].map(x=>`<div class="stat-card"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('');let vals=Array(12).fill(0);Object.entries(state.sessions).forEach(([k,v])=>{let d=new Date(k);if(d.getFullYear()===new Date().getFullYear())vals[d.getMonth()]+=v.pages||0});let max=Math.max(...vals,1);$('#bars').innerHTML=vals.map(v=>`<i title="${v} стр." style="height:${Math.max(5,v/max*100)}%"></i>`).join('');let authors={};state.books.forEach(b=>authors[b.author]=(authors[b.author]||0)+1);let topAuthors=Object.entries(authors).sort((a,b)=>b[1]-a[1]).slice(0,5);$('#libraryBreakdown').innerHTML=`<p><b>${state.books.length}</b> книг в библиотеке</p><p><b>${state.books.filter(b=>b.status==='reading').length}</b> читаются сейчас</p><p><b>${state.books.filter(b=>b.status==='planned').length}</b> в планах</p><p><b>${state.books.filter(b=>b.status==='abandoned').length}</b> брошено</p><hr>${topAuthors.map(x=>`<p>${esc(x[0])} · ${x[1]} книг</p>`).join('')}`;let ratings=Object.values(state.reviews).filter(x=>x.rating);let avg=ratings.length?(ratings.reduce((n,x)=>n+x.rating,0)/ratings.length).toFixed(1):'—';$('#advancedStats').innerHTML=[['Средняя оценка',avg,'из 5'],['Текущая серия',s.streak,'дней'],['Самая длинная сессия',fmtTime(Math.max(0,...state.history.map(x=>x.duration))), 'по истории']].map(x=>`<div class="stat-card"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('')}
function renderNotes(){let arr=state.notes.filter(n=>noteFilter==='all'||n.type===noteFilter);$('#notesGrid').innerHTML=arr.length?arr.map(n=>`<article class="note"><span class="type">${n.type==='quote'?'ЦИТАТА':n.type==='review'?'ОТЗЫВ':'МЫСЛЬ'}</span><blockquote>${esc(n.text)}</blockquote><small>${esc(n.book||'Без книги')} · ${fmtDate(n.date)}</small></article>`).join(''):'<div class="empty">Пока нет записей.</div>';$$('[data-note-filter]').forEach(x=>x.onclick=()=>{noteFilter=x.dataset.noteFilter;$$('[data-note-filter]').forEach(y=>y.classList.remove('active'));x.classList.add('active');renderNotes()})}
function addNote(){let d=modal(`<div class="modal-head"><h3>Новая запись</h3><button class="close">×</button></div><div class="modal-body"><form id="noteForm"><div class="form-grid"><div class="field"><label>Тип</label><select id="ntype"><option value="thought">Мысль</option><option value="quote">Цитата</option><option value="review">Отзыв</option></select></div><div class="field"><label>Книга</label><select id="nbook"><option value="">Без книги</option>${state.books.map(b=>`<option value="${b.id}">${esc(b.title)}</option>`).join('')}</select></div></div><div class="field" style="margin-top:12px"><label>Текст</label><textarea id="ntext" required></textarea></div><button class="btn" style="margin-top:14px">Сохранить</button></form></div>`);$('.close',d).onclick=()=>d.close();$('#noteForm',d).onsubmit=e=>{e.preventDefault();let b=state.books.find(x=>x.id===$('#nbook',d).value);state.notes.unshift({id:'n'+Date.now(),bookId:b?.id||null,book:b?.title||'Без книги',type:$('#ntype',d).value,text:$('#ntext',d).value,date:new Date().toISOString()});save();d.close();toast('Запись сохранена')}}
function renderGoals(){let year=new Date().getFullYear(),books=state.books.filter(b=>b.status==='finished'&&b.finishedAt&&new Date(b.finishedAt).getFullYear()===year).length;$('#yearGoalText').textContent=`${books} / ${state.goalBooks} книг`;$('#yearGoalBar').style.width=Math.min(100,books/state.goalBooks*100)+'%';$('#yearGoalLeft').textContent=`Осталось ${Math.max(0,state.goalBooks-books)} книг`;$('#goalBooks').value=state.goalBooks;$('#goalPages').value=state.goalPages;let today=state.sessions[dateKey()]?.pages||0;$('#goalMetrics').innerHTML=[['Страниц сегодня',today,`цель ${state.goalPages}`],['Прогресс цели',Math.round(Math.min(100,books/state.goalBooks*100))+'%','год'],['Дней с чтением',Object.keys(state.sessions).length,'за всё время']].map(x=>`<div class="stat-card"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('');$('#saveGoals').onclick=()=>{state.goalBooks=Math.max(1,+$('#goalBooks').value||30);state.goalPages=Math.max(1,+$('#goalPages').value||20);save();toast('Цели сохранены')}}
function renderCollections(){let booksBy=(ids=[])=>state.books.filter(b=>ids.includes(b.id));$('#collectionsGrid').innerHTML=state.collections.length?state.collections.map(c=>`<div class="goal-card"><span class="kicker">КОЛЛЕКЦИЯ</span><h3>${esc(c.name)}</h3><p>${c.bookIds.length} книг</p><div class="actions"><button class="secondary" data-col="${c.id}">Открыть</button><button class="icon-btn" data-delcol="${c.id}">Удалить</button></div></div>`).join(''):'<div class="empty">Создай первую коллекцию: «Любимые», «2026», «Психология» или любую свою.</div>';$('#collectionsGrid').querySelectorAll('[data-col]').forEach(x=>x.onclick=()=>openCollection(x.dataset.col));$('#collectionsGrid').querySelectorAll('[data-delcol]').forEach(x=>x.onclick=()=>{state.collections=state.collections.filter(c=>c.id!==x.dataset.delcol);save()})}
function addCollection(){let name=prompt('Название коллекции');if(!name)return;let ids=state.books.filter(b=>b.status==='reading').map(b=>b.id);state.collections.push({id:'c'+Date.now(),name,bookIds:ids});save();toast('Коллекция создана')}
function openCollection(id){let c=state.collections.find(x=>x.id===id);if(!c)return;let arr=state.books.filter(b=>c.bookIds.includes(b.id));let d=modal(`<div class="modal-head"><h3>${esc(c.name)}</h3><button class="close">×</button></div><div class="modal-body"><div class="books">${arr.length?arr.map(bookCard).join(''):'<div class="empty">Коллекция пока пустая.</div>'}</div></div>`);$('.close',d).onclick=()=>d.close()}
function renderSeries(){let map=state.series.map(s=>({...s,items:state.books.filter(b=>s.bookIds.includes(b.id))}));$('#seriesGrid').innerHTML=map.length?map.map(s=>`<div class="goal-card"><span class="kicker">СЕРИЯ</span><h3>${esc(s.name)}</h3><p>${s.items.filter(b=>b.status==='finished').length} / ${s.items.length} прочитано</p><div class="progress"><i style="width:${s.items.length?s.items.filter(b=>b.status==='finished').length/s.items.length*100:0}%"></i></div><div style="margin-top:12px">${s.items.map(b=>`<div style="padding:6px 0">${esc(b.title)}</div>`).join('')}</div></div>`).join(''):'<div class="empty">Добавь серию и выбери книги из библиотеки.</div>'}
function addSeries(){if(!state.books.length){toast('Сначала добавь книги');return}let name=prompt('Название серии');if(!name)return;let raw=prompt('Введи номера книг через запятую, например: 1,2,3');let ids=(raw||'').split(',').map(x=>state.books[+x.trim()-1]?.id).filter(Boolean);state.series.push({id:'s'+Date.now(),name,bookIds:ids});save();toast('Серия создана')}
function achievements(){let s=stats();return [['📖','Первая книга',s.books>=1],['📜','100 страниц',s.pages>=100],['⏱','Первый час',s.time>=3600],['📚','5 книг',s.books>=5],['🏆','1000 страниц',s.pages>=1000],['🔥','7 дней подряд',s.streak>=7],['✦','Первая сессия',state.history.length>=1],['⭐','Оценил книгу',Object.keys(state.reviews).length>=1]]}
function renderProfile(){let p=state.profile;$('#profileName').textContent=p.name||'Читатель';$('#profileNameInput').value=p.name||'';$('#profileEmail').textContent=user?.email||'Локальный профиль';$('#profilePhoto').src=p.avatar||'hero-library.png';let s=stats();$('#profileStats').innerHTML=[['Прочитано книг',s.books,'завершённых'],['Страниц',s.pages,'в библиотеке'],['Время чтения',fmtTime(s.time),'по сессиям'],['Серия',s.streak,'дней подряд']].map(x=>`<div class="stat-card"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('');$('#achievements').innerHTML=achievements().map(x=>`<div class="achievement ${x[2]?'':'locked'}"><div class="medal">${x[0]}</div><b>${x[1]}</b></div>`).join('');$('#saveProfile').onclick=()=>{state.profile.name=$('#profileNameInput').value.trim()||'Читатель';save();toast('Профиль сохранён')};$('#avatarInput').onchange=async e=>{if(e.target.files[0]){state.profile.avatar=await resizeImage(e.target.files[0]);save();toast('Аватар обновлён')}}}
function exportAll(){let blob=new Blob([JSON.stringify({version:4,exportedAt:new Date().toISOString(),...state},null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sashok-stishok-backup.json';a.click();URL.revokeObjectURL(a.href);toast('Backup скачан')}
function renderBackup(){$('#exportAll').onclick=exportAll;$('#importAll').onclick=()=>{let f=$('#importFile').files[0];if(!f){toast('Выбери JSON-файл');return}let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);if(!d.books)throw 0;state={...state,...d};save();toast('Данные восстановлены')}catch{toast('Не удалось прочитать backup')}};r.readAsText(f)}}
function auth(){if(user){location.href='profile.html';return}let d=modal(`<div class="modal-head"><div><span class="kicker">АККАУНТ</span><h3>Войти в Сашок стишок</h3></div><button class="close">×</button></div><div class="modal-body"><form id="authForm"><div class="field"><label>Email</label><input id="authEmail" type="email" required></div><div class="field" style="margin-top:12px"><label>Пароль</label><input id="authPass" type="password" minlength="6" required></div><button class="btn" style="margin-top:14px">Войти</button><p id="authMsg" style="color:var(--muted)">Нет аккаунта? После регистрации можно синхронизировать библиотеку на всех устройствах.</p><button type="button" class="secondary" id="signup">Создать профиль</button></form></div>`);$('.close',d).onclick=()=>d.close();$('#authForm',d).onsubmit=async e=>{e.preventDefault();if(!cloud){$('#authMsg',d).textContent='Supabase не подключён.';return}let r=await cloud.auth.signInWithPassword({email:$('#authEmail',d).value,password:$('#authPass',d).value});if(r.error)$('#authMsg',d).textContent=r.error.message;else{d.close();toast('Добро пожаловать')}};$('#signup',d).onclick=async()=>{if(!cloud)return;let email=$('#authEmail',d).value,pass=$('#authPass',d).value;if(!email||!pass){$('#authMsg',d).textContent='Заполни email и пароль';return}let r=await cloud.auth.signUp({email,password:pass,options:{data:{display_name:email.split('@')[0]}}});$('#authMsg',d).textContent=r.error?r.error.message:'Проверь почту и подтверди регистрацию.'}}
function renderCurrent(){let p=document.body.dataset.page;try{if(p==='home')renderHome();if(p==='library')renderLibrary();if(p==='discover')renderDiscover();if(p==='session')renderSession();if(p==='calendar'){renderCalendar();$('#prevMonth').onclick=()=>{month.setMonth(month.getMonth()-1);renderCalendar()};$('#nextMonth').onclick=()=>{month.setMonth(month.getMonth()+1);renderCalendar()}}if(p==='stats')renderStats();if(p==='notes'){renderNotes();$('#addNote').onclick=addNote}if(p==='goals')renderGoals();if(p==='collections'){renderCollections();$('#addCollection').onclick=addCollection}if(p==='series'){renderSeries();$('#addSeries').onclick=addSeries}if(p==='profile')renderProfile();if(p==='backup')renderBackup();}catch(e){console.error(e)}}
$('#theme')?.addEventListener('click',()=>{state.theme=state.theme==='dark'?'light':'dark';document.documentElement.classList.toggle('dark',state.theme==='dark');saveLocal()});$('#authOpen')?.addEventListener('click',auth);document.documentElement.classList.toggle('dark',state.theme==='dark');initCloud().then(()=>renderCurrent());
